repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2'
    hooks:
      - id: poetry-check
        name: poetry check
      - id: poetry-lock
        name: poetry lock
        args: [ "--no-update" ]
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
